[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040_SELFDEBUG --speed 1000 target/thumbv6m-none-eabi/release/cec-adapter"
#runner = "probe-rs-cli run --chip RP2040_SELFDEBUG --speed 1000"
#runner = "probe-rs-cli download --chip RP2040_SELFDEBUG --speed 1000"
#runner = "elf2uf2-rs --verbose -d"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
